import jsPDF from 'jspdf';

export const generateAdherenceReport = (patientData, logs, inventoryData) => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(14, 165, 233); // Primary blue
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('Smart Medicine Dispenser', 105, 20, { align: 'center' });
    doc.setFontSize(14);
    doc.text('60-Day Adherence Report', 105, 30, { align: 'center' });

    // Patient Information
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Patient Information', 20, 55);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(`Name: ${patientData.name || 'N/A'}`, 20, 65);
    doc.text(`Patient ID: ${patientData.id || 'N/A'}`, 20, 72);
    doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, 20, 79);

    // Adherence Statistics
    const totalDoses = logs.length;
    const takenDoses = logs.filter(log => log.event === 'taken').length;
    const missedDoses = logs.filter(log => log.event === 'missed').length;
    const adherenceRate = totalDoses > 0 ? ((takenDoses / totalDoses) * 100).toFixed(1) : 0;

    doc.setFont(undefined, 'bold');
    doc.setFontSize(12);
    doc.text('Adherence Statistics (Last 60 Days)', 20, 95);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(`Total Scheduled Doses: ${totalDoses}`, 20, 105);
    doc.text(`Doses Taken: ${takenDoses}`, 20, 112);
    doc.text(`Doses Missed: ${missedDoses}`, 20, 119);
    doc.text(`Adherence Rate: ${adherenceRate}%`, 20, 126);

    // Verification Success Rates
    const verificationStats = logs.reduce((acc, log) => {
        if (log.verification) {
            acc.face += log.verification.face ? 1 : 0;
            acc.ir += log.verification.ir ? 1 : 0;
            acc.load += log.verification.load ? 1 : 0;
            acc.total += 1;
        }
        return acc;
    }, { face: 0, ir: 0, load: 0, total: 0 });

    if (verificationStats.total > 0) {
        doc.setFont(undefined, 'bold');
        doc.setFontSize(12);
        doc.text('Verification Success Rates', 20, 142);

        doc.setFont(undefined, 'normal');
        doc.setFontSize(10);
        const faceRate = ((verificationStats.face / verificationStats.total) * 100).toFixed(1);
        const irRate = ((verificationStats.ir / verificationStats.total) * 100).toFixed(1);
        const loadRate = ((verificationStats.load / verificationStats.total) * 100).toFixed(1);

        doc.text(`Face Recognition: ${faceRate}%`, 20, 152);
        doc.text(`IR Sensor: ${irRate}%`, 20, 159);
        doc.text(`Load Cell: ${loadRate}%`, 20, 166);
    }

    // Inventory Status
    doc.setFont(undefined, 'bold');
    doc.setFontSize(12);
    doc.text('Current Inventory Status', 20, 182);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(`Virtual Stock: ${inventoryData?.virtual_stock || 0} doses`, 20, 192);
    doc.text(`Physical Slots: ${inventoryData?.physical_slots || 7} slots`, 20, 199);

    // Recent Activity Log (Last 10 entries)
    doc.addPage();
    doc.setFont(undefined, 'bold');
    doc.setFontSize(12);
    doc.text('Recent Activity Log (Last 10 Entries)', 20, 20);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(9);
    let yPos = 30;

    const recentLogs = logs.slice(0, 10);
    recentLogs.forEach((log, index) => {
        const date = new Date(log.created_at || log.timestamp).toLocaleString();
        const status = log.event === 'taken' ? '✓ Taken' : '✗ Missed';
        const verification = log.verification
            ? `F:${log.verification.face ? '✓' : '✗'} IR:${log.verification.ir ? '✓' : '✗'} L:${log.verification.load ? '✓' : '✗'}`
            : 'N/A';

        doc.text(`${index + 1}. ${date}`, 20, yPos);
        doc.text(`Status: ${status}`, 20, yPos + 7);
        doc.text(`Verification: ${verification}`, 20, yPos + 14);

        yPos += 25;

        if (yPos > 270 && index < recentLogs.length - 1) {
            doc.addPage();
            yPos = 20;
        }
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Page ${i} of ${pageCount} | Generated by Smart Medicine Dispenser System`,
            105,
            290,
            { align: 'center' }
        );
    }

    // Save the PDF
    const fileName = `SMD_Report_${patientData.name || 'Patient'}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
};
