export const generatePDFReport = (patientData, stats) => {
    // This function creates a printable window to simulate a PDF report
    // A real implementation would use jspdf or react-pdf

    const printWindow = window.open('', '', 'height=800,width=800');

    const htmlContent = `
        <html>
        <head>
            <title>Medical Report - ${patientData.patientName}</title>
            <style>
                body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
                .header { border-bottom: 2px solid #14B8A6; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
                .title { font-size: 24px; font-weight: bold; color: #0F766E; text-transform: uppercase; }
                .meta { text-align: right; font-size: 12px; color: #666; }
                
                .section { margin-bottom: 30px; }
                .section-title { font-size: 14px; font-weight: bold; color: #14B8A6; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-bottom: 15px; text-transform: uppercase; }
                
                .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
                .field { margin-bottom: 10px; }
                .label { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; }
                .value { font-size: 14px; font-weight: 500; }
                
                .stats-box { background: #F0FDFA; border: 1px solid #CCFBF1; padding: 15px; border-radius: 8px; }
                .stat-row { display: flex; justify-content: space-between; margin-bottom: 8px; border-bottom: 1px dashed #ddd; padding-bottom: 8px; }
                .stat-row:last-child { border: none; }
                
                .footer { margin-top: 50px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
            </style>
        </head>
        <body>
            <div class="header">
                <div>
                    <div class="title">Personal Medical Record</div>
                    <div style="font-size: 12px; margin-top: 5px;">Generated by Smart Medicine Dispenser</div>
                </div>
                <div class="meta">
                    Report Date: ${new Date().toLocaleDateString()}<br>
                    Ref ID: #${Math.random().toString(36).substr(2, 9).toUpperCase()}
                </div>
            </div>

            <div class="section">
                <div class="section-title">Patient Demographics</div>
                <div class="grid">
                    <div>
                        <div class="field"><div class="label">Full Name</div><div class="value">${patientData.patientName}</div></div>
                        <div class="field"><div class="label">Date of Birth</div><div class="value">${patientData.dob}</div></div>
                        <div class="field"><div class="label">Gender</div><div class="value">${patientData.gender}</div></div>
                        <div class="field"><div class="label">Marital Status</div><div class="value">${patientData.maritalStatus}</div></div>
                    </div>
                    <div>
                        <div class="field"><div class="label">Address</div><div class="value">${patientData.address || 'N/A'}</div></div>
                        <div class="field"><div class="label">Ethnicity</div><div class="value">${patientData.ethnicity || 'N/A'}</div></div>
                        <div class="field"><div class="label">Religion</div><div class="value">${patientData.religion || 'N/A'}</div></div>
                    </div>
                </div>
            </div>

            <div class="section">
                <div class="section-title">Guardian / Caregiver Information</div>
                <div class="grid">
                    <div>
                        <div class="field"><div class="label">Guardian Name</div><div class="value">${patientData.guardianName}</div></div>
                        <div class="field"><div class="label">Relationship</div><div class="value">${patientData.relationship}</div></div>
                        <div class="field"><div class="label">Contact Email</div><div class="value">${patientData.guardianEmail}</div></div>
                    </div>
                    <div>
                        <div class="field"><div class="label">Phone Number</div><div class="value">${patientData.guardianPhone}</div></div>
                        <div class="field"><div class="label">Guardian Address</div><div class="value">${patientData.guardianAddress || 'Same as Patient'}</div></div>
                    </div>
                </div>
            </div>

            <div class="section">
                <div class="section-title">Medication Adherence Report</div>
                <div class="stats-box">
                    <div class="stat-row">
                        <span>Weekly Avg. Adherence</span>
                        <strong>${stats.weeklyAdherence}%</strong>
                    </div>
                    <div class="stat-row">
                        <span>Monthly Avg. Adherence</span>
                        <strong>${stats.monthlyAdherence}%</strong>
                    </div>
                    <div class="stat-row">
                        <span>Total Doses Taken (This Month)</span>
                        <strong>${stats.takenCount}</strong>
                    </div>
                    <div class="stat-row">
                        <span>Total Doses Missed (This Month)</span>
                        <strong style="color: #F43F5E;">${stats.missedCount}</strong>
                    </div>
                </div>
            </div>
            
            <div class="footer">
                This report is automatically generated. Please consult with a medical professional for advice.<br>
                SMD Medical Systems Inc.
            </div>
        </body>
        </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.print();
};
